# Generated by Django 3.1.6 on 2021-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
