# Generated by Django 3.1.6 on 2021-02-04 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0002_auto_20210204_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='data_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
