# Generated by Django 3.1.6 on 2021-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('disciplina', '0003_disciplina_data_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='usuario',
            field=models.ManyToManyField(to='user.Usuario'),
        ),
    ]
