# Generated by Django 3.1.6 on 2021-02-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0004_auto_20210206_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='usuario',
            field=models.ManyToManyField(to='disciplina.Usuario'),
        ),
    ]
