# Generated by Django 3.1.6 on 2021-02-11 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disciplina', '0007_auto_20210209_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='data_reserva',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='usuario',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Início'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='descricao_longa',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Atalho'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='titulo',
            field=models.TextField(max_length=25, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=30, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovdo'), (2, 'Cancelado')], default=0, verbose_name='Situação')),
                ('dataReserva', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao', to='disciplina.disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'unique_together': {('usuario', 'disciplina')},
            },
        ),
    ]
