# Generated by Django 3.1.6 on 2021-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0008_auto_20210211_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='disciplina',
            field=models.ManyToManyField(blank=True, null=True, to='disciplina.Disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='Atalho'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'adm'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=15, verbose_name='Tipo do usuario'),
        ),
    ]
