# Generated by Django 3.1.6 on 2021-02-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0010_auto_20210213_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='disciplina',
        ),
    ]
