# Generated by Django 3.1.6 on 2021-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0011_remove_usuario_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='disciplina',
            field=models.ManyToManyField(blank=True, null=True, to='disciplina.Disciplina', verbose_name='Disciplina'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADM', 'adm'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=15, verbose_name='Tipo do usuario'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
