# Generated by Django 3.1.6 on 2021-02-16 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0018_auto_20210216_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.disciplina'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplina.usuario'),
        ),
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linguagem', to='disciplina.disciplina'),
        ),
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linguagem', to='disciplina.usuario'),
        ),
    ]
