# Generated by Django 3.1.6 on 2021-02-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0019_auto_20210216_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
