# Generated by Django 3.1.6 on 2021-02-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0021_usuariodisciplina_data_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_choice',
            field=models.CharField(choices=[('a', 'Adm'), ('p', 'Professor'), ('a', 'Aluno')], default=-1, max_length=1),
            preserve_default=False,
        ),
    ]
