# Generated by Django 3.1.6 on 2021-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0025_auto_20210218_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariodisciplina',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user_choice',
        ),
        migrations.AddField(
            model_name='usuario',
            name='aluno',
            field=models.BooleanField(blank=True, null=True, verbose_name='aluno'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='professor',
            field=models.BooleanField(blank=True, null=True, verbose_name='professor'),
        ),
    ]
