# Generated by Django 3.1.6 on 2021-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0026_auto_20210222_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data Cadastro'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='descricao_curta',
            field=models.TextField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Aguardando', 'Aguardando'), ('Aprovado', 'Aprovado'), ('Pendente', 'Pendente')], default='Aguardando', verbose_name='Situação'),
        ),
    ]
