# Generated by Django 3.1.6 on 2021-02-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0028_auto_20210224_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodisciplina',
            name='aceitarAgendamento',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='usuariodisciplina',
            name='agendamentoPendente',
            field=models.BooleanField(blank=True, null=True, verbose_name='Aguardando'),
        ),
    ]
