# Generated by Django 3.1.6 on 2021-02-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0029_auto_20210224_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='aceitarAgendamento',
        ),
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='agendamentoPendente',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_choice',
            field=models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default=-1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, verbose_name='User'),
        ),
    ]
