# Generated by Django 3.1.6 on 2021-02-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0030_auto_20210225_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_choice',
            field=models.CharField(choices=[('p', 'Professor'), ('a', 'Aluno')], max_length=1),
        ),
    ]
