# Generated by Django 3.1.6 on 2021-02-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0031_auto_20210225_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Senha'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Senha2'),
        ),
    ]
