# Generated by Django 3.1.6 on 2021-02-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0032_auto_20210225_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='user_choice',
            field=models.CharField(max_length=20, verbose_name='user_choice'),
        ),
    ]
