# Generated by Django 3.1.6 on 2021-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0034_auto_20210225_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('aluno', 'Aluno')], default='aluno', help_text='avaliar', max_length=10),
        ),
    ]
