# Generated by Django 3.1.6 on 2021-02-25 23:55

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0035_usuario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.CharField(blank=True, choices=[('professor', 'Professor'), ('aluno', 'Aluno')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30, verbose_name=django.contrib.auth.models.User),
        ),
    ]
