# Generated by Django 3.1.6 on 2021-02-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0042_auto_20210226_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='usuario',
        ),
    ]
