# Generated by Django 3.1.6 on 2021-03-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0043_remove_usuariodisciplina_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='disciplina',
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='UsuarioDisciplina',
        ),
    ]
