# Generated by Django 3.1.6 on 2021-03-01 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0044_auto_20210301_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
