# Generated by Django 3.1.6 on 2021-03-04 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0046_auto_20210301_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='disciplina.professor'),
            preserve_default=False,
        ),
    ]
