# Generated by Django 3.1.6 on 2021-03-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0048_remove_usuariodisciplina_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Cancelado', 'Cancelado')], default=0, verbose_name='Situação'),
        ),
    ]
