# Generated by Django 3.1.6 on 2021-03-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0053_auto_20210305_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
