# Generated by Django 3.1.6 on 2021-03-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0055_auto_20210305_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=1),
        ),
    ]
