# Generated by Django 3.1.6 on 2021-03-06 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0058_auto_20210305_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='professor',
        ),
    ]
