# Generated by Django 3.1.6 on 2021-03-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0061_auto_20210312_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
