# Generated by Django 3.1.6 on 2021-03-12 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0063_professor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
    ]
