# Generated by Django 3.1.6 on 2021-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0065_auto_20210313_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'Pendente'), ('a', 'Aprovado'), ('c', 'Cancelado')], default='p', max_length=1, verbose_name='Situação'),
        ),
    ]
