# Generated by Django 3.1.6 on 2021-03-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0066_auto_20210313_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Aprovado'), (2, 'Cancelado')], default=0, verbose_name='Situação'),
        ),
    ]
