# Generated by Django 3.1.6 on 2021-03-15 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0076_remove_usuariodisciplina_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='data_inicio',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='data_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Início'),
        ),
    ]
