# Generated by Django 3.1.6 on 2021-03-15 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0077_auto_20210315_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='professor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='Professor', to='disciplina.professor'),
            preserve_default=False,
        ),
    ]
