# Generated by Django 3.1.6 on 2021-03-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0078_auto_20210315_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='professor',
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='disciplina.usuario'),
            preserve_default=False,
        ),
    ]
