# Generated by Django 3.1.6 on 2021-03-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0080_remove_professor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='professor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='disciplina.professor'),
        ),
    ]
