# Generated by Django 3.1.6 on 2021-03-16 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0082_auto_20210316_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ussuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
