# Generated by Django 3.1.6 on 2021-03-16 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0083_disciplina_ussuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='ussuario',
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='disciplina.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='prof', to='disciplina.professor'),
            preserve_default=False,
        ),
    ]
