# Generated by Django 3.1.6 on 2021-03-16 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0084_auto_20210316_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariodisciplina',
            unique_together={('usuario', 'disciplina')},
        ),
        migrations.RemoveField(
            model_name='usuariodisciplina',
            name='professor',
        ),
    ]
