# Generated by Django 3.1.6 on 2021-03-17 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0085_auto_20210316_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='profe', to='disciplina.professor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usuariodisciplina',
            unique_together=set(),
        ),
    ]
