# Generated by Django 3.1.6 on 2021-03-17 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0086_auto_20210316_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.professor'),
        ),
    ]
