# Generated by Django 3.1.6 on 2021-03-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0089_auto_20210317_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='linguagem', to='disciplina.professor'),
            preserve_default=False,
        ),
    ]
