# Generated by Django 3.1.6 on 2021-03-17 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0090_auto_20210317_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariodisciplina',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplina.professor'),
        ),
    ]
