# Generated by Django 3.1.6 on 2021-02-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0005_auto_20210206_2159'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
